# Generated by Django 4.2.26 on 2025-11-22 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("functions", "0005_functionrunsummary"),
        ("functions", "0006_annotationrequest_run_summary"),
        ("functions", "0007_functionrunstatus_v2"),
        ("functions", "0008_alter_annotationrequest_status_alter_function_kind_and_more"),
        ("functions", "0009_alter_annotationrequest_run_status"),
    ]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("functions", "0004_enable_sam2_tracker_batching"),
        ("engine", "0096_trackedshape_function_run_id"),
        ("engine", "0095_fix_related_names"),
    ]

    operations = [
        migrations.CreateModel(
            name="FunctionRunSummary",
            fields=[
                ("run_id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("total_requests", models.PositiveIntegerField(default=0)),
                ("completed_requests", models.PositiveIntegerField(default=0)),
                ("failed_requests", models.PositiveIntegerField(default=0)),
                ("cancelled_requests", models.PositiveIntegerField(default=0)),
                ("expected_frames", models.PositiveIntegerField(blank=True, null=True)),
                ("completed_frames", models.PositiveIntegerField(default=0)),
                ("progress", models.FloatField(default=0.0)),
                ("active_request_id", models.UUIDField(blank=True, null=True)),
                ("active_request_type", models.CharField(blank=True, max_length=64)),
                ("active_request_updated_at", models.DateTimeField(blank=True, null=True)),
                ("active_request_progress", models.FloatField(default=0.0)),
                ("active_request_frame_span", models.PositiveIntegerField(default=0)),
                ("failed_request_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "function",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="run_summaries",
                        to="functions.function",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="function_run_summaries",
                        to="engine.job",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="function_run_summaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="function_run_summaries",
                        to="engine.task",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["owner", "run_id"], name="functions_f_owner__42d17c_idx"),
                    models.Index(
                        fields=["function", "status"], name="functions_f_functi_f76030_idx"
                    ),
                    models.Index(fields=["job"], name="functions_f_job_id_2f5341_idx"),
                ],
            },
        ),
        migrations.AddField(
            model_name="annotationrequest",
            name="run_summary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotation_requests",
                to="functions.functionrunsummary",
            ),
        ),
        migrations.AddIndex(
            model_name="annotationrequest",
            index=models.Index(fields=["run_summary"], name="functions_a_run_sum_7d413e_idx"),
        ),
        migrations.RenameModel(
            old_name="FunctionRunSummary",
            new_name="FunctionRunStatus",
        ),
        migrations.RenameField(
            model_name="annotationrequest",
            old_name="run_summary",
            new_name="run_status",
        ),
        migrations.RemoveIndex(
            model_name="annotationrequest",
            name="functions_a_run_sum_7d413e_idx",
        ),
        migrations.RemoveIndex(
            model_name="annotationrequest",
            name="functions_a_func_id_8c6b8b_idx",
        ),
        migrations.RemoveIndex(
            model_name="annotationrequest",
            name="functions_a_task_id_a61bf9_idx",
        ),
        migrations.AddIndex(
            model_name="annotationrequest",
            index=models.Index(fields=["run_status"], name="functions_ar_run_status_idx"),
        ),
        migrations.AddIndex(
            model_name="annotationrequest",
            index=models.Index(fields=["function", "status"], name="functions_ar_fn_status_idx"),
        ),
        migrations.AddIndex(
            model_name="annotationrequest",
            index=models.Index(fields=["task"], name="functions_ar_task_idx"),
        ),
        migrations.AddField(
            model_name="functionrunstatus",
            name="last_error",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="functionrunstatus",
            name="payload_version",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.RemoveIndex(
            model_name="functionrunstatus",
            name="functions_f_owner__42d17c_idx",
        ),
        migrations.RemoveIndex(
            model_name="functionrunstatus",
            name="functions_f_functi_f76030_idx",
        ),
        migrations.RemoveIndex(
            model_name="functionrunstatus",
            name="functions_f_job_id_2f5341_idx",
        ),
        migrations.AddIndex(
            model_name="functionrunstatus",
            index=models.Index(fields=["owner", "run_id"], name="functions_frs_owner_run_idx"),
        ),
        migrations.AddIndex(
            model_name="functionrunstatus",
            index=models.Index(fields=["function", "status"], name="functions_frs_fn_status_idx"),
        ),
        migrations.AddIndex(
            model_name="functionrunstatus",
            index=models.Index(
                fields=["job", "status", "-updated_at"], name="functions_frs_job_status_idx"
            ),
        ),
        migrations.RemoveIndex(
            model_name="function",
            name="functions_f_owner_c5c23a_idx",
        ),
        migrations.RemoveIndex(
            model_name="function",
            name="functions_f_kind_c4c73d_idx",
        ),
        migrations.AddIndex(
            model_name="function",
            index=models.Index(fields=["owner"], name="functions_fn_owner_idx"),
        ),
        migrations.AddIndex(
            model_name="function",
            index=models.Index(fields=["kind"], name="functions_fn_kind_idx"),
        ),
        migrations.AlterField(
            model_name="annotationrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("done", "Done"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="function",
            name="kind",
            field=models.CharField(
                choices=[
                    ("detector", "Detector"),
                    ("interactor", "Interactor"),
                    ("reid", "Reid"),
                    ("tracker", "Tracker"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="functionrunstatus",
            name="function",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="run_statuses",
                to="functions.function",
            ),
        ),
        migrations.AlterField(
            model_name="functionrunstatus",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="function_run_statuses",
                to="engine.job",
            ),
        ),
        migrations.AlterField(
            model_name="functionrunstatus",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="function_run_statuses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="functionrunstatus",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="function_run_statuses",
                to="engine.task",
            ),
        ),
        migrations.AlterField(
            model_name="annotationrequest",
            name="run_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotation_requests",
                to="functions.functionrunstatus",
            ),
        ),
    ]
