# Generated by Django 4.2.26 on 2025-11-18 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("engine", "0096_trackedshape_function_run_id"),
        ("functions", "0007_functionrunstatus_v2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotationrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("running", "Running"),
                    ("done", "Done"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="function",
            name="kind",
            field=models.CharField(
                choices=[
                    ("detector", "Detector"),
                    ("interactor", "Interactor"),
                    ("reid", "Reid"),
                    ("tracker", "Tracker"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="functionrunstatus",
            name="function",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="run_statuses",
                to="functions.function",
            ),
        ),
        migrations.AlterField(
            model_name="functionrunstatus",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="function_run_statuses",
                to="engine.job",
            ),
        ),
        migrations.AlterField(
            model_name="functionrunstatus",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="function_run_statuses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="functionrunstatus",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="function_run_statuses",
                to="engine.task",
            ),
        ),
    ]
