# Generated by Django 4.2.26 on 2025-11-18 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("functions", "0008_alter_annotationrequest_status_alter_function_kind_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotationrequest",
            name="run_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotation_requests",
                to="functions.functionrunstatus",
            ),
        ),
    ]
