# Generated by Django 4.2.21 on 2025-11-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0095_fix_related_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackedshape",
            name="function_run_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
